using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Littorio.Final
{
    public static class Countries
    {
        public static Dictionary<string, string> countryCodesMapping = new Dictionary<string, string>() {
                    { "001", "World" },
                      { "029", "Caribbean" },
                      { "419", "Latin America" },
                      { "AF", "Afghanistan" },
                      { "AL", "Albania" },
                      { "AE", "United Arab Emirates" },
                      { "AR", "Argentina" },
                      { "AM", "Armenia" },
                      { "AU", "Australia" },
                      { "AT", "Austria" },
                      { "AZ", "Azerbaijan" },
                      { "BE", "Belgium" },
                      { "BD", "Bangladesh" },
                      { "BG", "Bulgaria" },
                      { "BH", "Bahrain" },
                      { "BA", "Bosnia and Herzegovina" },
                      { "BY", "Belarus" },
                      { "BZ", "Belize" },
                      { "BO", "Bolivia" },
                      { "BR", "Brazil" },
                      { "BN", "Brunei" },
                      { "BT", "Bhutan" },
                      { "BW", "Botswana" },
                      { "CA", "Canada" },
                      { "CH", "Switzerland" },
                      { "CL", "Chile" },
                      { "CN", "China" },
                      { "CI", "Cote d’Ivoire" },
                      { "CM", "Cameroon" },
                      { "CD", "Congo (DRC)" },
                      { "CO", "Colombia" },
                      { "CR", "Costa Rica" },
                      { "CU", "Cuba" },
                      { "CZ", "Czech Republic" },
                      { "DE", "Germany" },
                      { "DJ", "Djibouti" },
                      { "DK", "Denmark" },
                      { "DO", "Dominican Republic" },
                      { "DZ", "Algeria" },
                      { "EC", "Ecuador" },
                      { "EG", "Egypt" },
                      { "ER", "Eritrea" },
                      { "ES", "Spain" },
                      { "EE", "Estonia" },
                      { "ET", "Ethiopia" },
                      { "FI", "Finland" },
                      { "FR", "France" },
                      { "FO", "Faroe Islands" },
                      { "GB", "United Kingdom" },
                      { "GE", "Georgia" },
                      { "GR", "Greece" },
                      { "GL", "Greenland" },
                      { "GT", "Guatemala" },
                      { "HK", "Hong Kong SAR" },
                      { "HN", "Honduras" },
                      { "HR", "Croatia" },
                      { "HT", "Haiti" },
                      { "HU", "Hungary" },
                      { "ID", "Indonesia" },
                      { "IN", "India" },
                      { "IE", "Ireland" },
                      { "IR", "Iran" },
                      { "IQ", "Iraq" },
                      { "IS", "Iceland" },
                      { "IL", "Israel" },
                      { "IT", "Italy" },
                      { "JM", "Jamaica" },
                      { "JO", "Jordan" },
                      { "JP", "Japan" },
                      { "KZ", "Kazakhstan" },
                      { "KE", "Kenya" },
                      { "KG", "Kyrgyzstan" },
                      { "KH", "Cambodia" },
                      { "KR", "Korea" },
                      { "KW", "Kuwait" },
                      { "LA", "Laos" },
                      { "LB", "Lebanon" },
                      { "LY", "Libya" },
                      { "LI", "Liechtenstein" },
                      { "LK", "Sri Lanka" },
                      { "LT", "Lithuania" },
                      { "LU", "Luxembourg" },
                      { "LV", "Latvia" },
                      { "MO", "Macao SAR" },
                      { "MA", "Morocco" },
                      { "MC", "Monaco" },
                      { "MD", "Moldova" },
                      { "MV", "Maldives" },
                      { "MX", "Mexico" },
                      { "MK", "Macedonia, FYRO" },
                      { "ML", "Mali" },
                      { "MT", "Malta" },
                      { "MM", "Myanmar" },
                      { "ME", "Montenegro" },
                      { "MN", "Mongolia" },
                      { "MY", "Malaysia" },
                      { "NG", "Nigeria" },
                      { "NI", "Nicaragua" },
                      { "NL", "Netherlands" },
                      { "NO", "Norway" },
                      { "NP", "Nepal" },
                      { "NZ", "New Zealand" },
                      { "OM", "Oman" },
                      { "PK", "Pakistan" },
                      { "PA", "Panama" },
                      { "PE", "Peru" },
                      { "PH", "Philippines" },
                      { "PL", "Poland" },
                      { "PR", "Puerto Rico" },
                      { "PT", "Portugal" },
                      { "PY", "Paraguay" },
                      { "QA", "Qatar" },
                      { "RE", "Reunion" },
                      { "RO", "Romania" },
                      { "RU", "Russia" },
                      { "RW", "Rwanda" },
                      { "SA", "Saudi Arabia" },
                      { "SN", "Senegal" },
                      { "SG", "Singapore" },
                      { "SV", "El Salvador" },
                      { "SO", "Somalia" },
                      { "RS", "Serbia" },
                      { "SK", "Slovakia" },
                      { "SI", "Slovenia" },
                      { "SE", "Sweden" },
                      { "SY", "Syria" },
                      { "TH", "Thailand" },
                      { "TJ", "Tajikistan" },
                      { "TM", "Turkmenistan" },
                      { "TT", "Trinidad and Tobago" },
                      { "TN", "Tunisia" },
                      { "TR", "Turkey" },
                      { "TW", "Taiwan" },
                      { "UA", "Ukraine" },
                      { "UY", "Uruguay" },
                      { "US", "United States" },
                      { "UZ", "Uzbekistan" },
                      { "VE", "Venezuela" },
                      { "VN", "Vietnam" },
                      { "YE", "Yemen" },
                      { "ZA", "South Africa" },
                      { "ZW", "Zimbabwe" },
                    };

    }
}
